project_id = "ltgampdtawuefwwayncx"

[functions.check-email]
verify_jwt = false

[functions.chat-alibaba]
verify_jwt = false


[functions.slides-api]
verify_jwt = false

[functions.referral-track]
verify_jwt = false

[functions.notify-user]
verify_jwt = true

[functions.check-cf-secrets]
verify_jwt = false

[functions.pipedream-connect]
verify_jwt = true



